######################################################################
##
## Filename: Rs232RefComp.udo
## Created on: Sat May 07 11:27:08 AM Eastern Daylight Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
